-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "csv",
      "dockerfile",
      "git_config",
      "html",
      "java",
      "javascript",
      "json",
      "latex",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "norg",
      "printf",
      "python",
      "r",
      "regex",
      "solidity",
      "sql",
      "ssh_config",
      "toml",
      "tmux",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
